Log:
  Level: error

Mongo:
  DSN: mongodb://127.0.0.1:27017/
  DB: armv-main

Workers: 16

Converter:
  Registry: /Users/alexis/workspace/rtlabs/sdf-converter/data/registry.xlsx
  Dir:
    Template: /Users/alexis/workspace/rtlabs/sdf-converter/template
    Artefact: /Users/alexis/workspace/rtlabs/sdf-converter/data/artefact
    Tmp: /Users/alexis/workspace/rtlabs/sdf-converter/data/tmp
